apiVersion: v1
kind: Secret
metadata:
  name: mysecret2
type: Opaque
stringData:
  username: "admin"
  password: "123"
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret2
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret2
            key: password
    volumeMounts:
    - name: test
      mountPath: /opt
      readOnly: true
  volumes:
  - name: test
    secret:
      secretName: mysecret2
      items:
      - key: username
        path: user.txt
      - key: password
        path: password.txt