apiVersion: v1
kind: Pod
metadata:
  name: pachi
spec:
  containers:
    - name: pod1
      image: python:3.6-alpine
      command: ['sh','-c','echo container1 > index.html && python -m http.server 8082']
    - name: pod2
      image: python:3.6-alpine
      command: ['sh','-c','echo container2 > index.html && python -m http.server 8083']