apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-test
  labels:
    app: guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: pod1
          image: python:3.6-alpine
          command: ['sh','-c','echo container1 > index.html && python -m http.server 8082']
        - name: pod2
          image: python:3.6-alpine
          command: ['sh','-c','echo container2 > index.html && python -m http.server 8083']
